name: Terraform CI

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2  # Specify the version you need

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
    - name: Render Helm values
      run: |
        sed -i 's/{{ .Values.CLIENT_SECRET }}/$CLIENT_SECRET/g' values.yaml
        sed -i 's/{{ .Values.KEYCLOAK_ADMIN }}/$KEYCLOAK_ADMIN/g' values.yaml
        sed -i 's/{{ .Values.KEYCLOAK_PASSWORD }}/$KEYCLOAK_PASSWORD/g' values.yaml
        sed -i 's/{{ .Values.POSTGRES_DB_USER }}/$POSTGRES_DB_USER/g' values.yaml
        sed -i 's/{{ .Values.POSTGRES_DB_PASSWORD }}/$POSTGRES_DB_PASSWORD/g' values.yaml
        sed -i 's/{{ .Values.CLUSTER_ISSUER_EMAIL }}/$CLUSTER_ISSUER_EMAIL/g' values.yaml
      env:
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
        KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
        POSTGRES_DB_USER: ${{ secrets.POSTGRES_DB_USER }}
        POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
        CLUSTER_ISSUER_EMAIL: ${{ secrets.CLUSTER_ISSUER_EMAIL }}
        
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_exo_key: ${{ secrets.TF_VAR_EXO_KEY }}
        TF_VAR_exo_secret: ${{ secrets.TF_VAR_EXO_SECRET }}

